name: Your New Jekyll Knowledge Base
markdown: redcarpet
pygments: true


# Permalinks
permalink: pretty

# Exclude the following files/directories from being converted
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md']

# Variables
jekyllkb_version: 0.1.0-pre

#########################
# Plugin: jekyll-assets #
#########################

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    #- _assets/fonts/bootstrap
    #- _assets/fonts/font-awesome

  # Minify and Compress Assets
  #js_compressor: uglifier
  #css_compressor: sass
  compress:
    css: sass
    js: uglifier

  # Disable asset gzip
  gzip: false
